### ISSUE TITLE
Examp folder being created

### ISSUE THREAD

**Issue by shairozan** [metrumresearchgroup/babylon#104]
When calling models in relative pathing, for some reason (sometimes) we occasionally get an `examp` directory that contains what appears to be the nonmem XML output.

**Comment by shairozan** [comment]
Whenever I run the model series that I've been using for BBI, I don't get this experience, but I'll try nesting 5-6 directories down to verify. Secondarily, I see it in the ACOP test data. Wondering if it might actually be something about the file or environmental? Devin has verified that it occurs on his mac as well.

**Comment by shairozan** [comment]
```
.
├── babylon.yaml
├── bbi
├── go_build_main_go
├── goreleaser.yml
├── main.go
└── tmp
    └── tmp
        ├── tm
        └── tmp
            └── acop
                ├── acop
                │   ├── acop.clt
                │   ├── acop.coi
                │   ├── acop.cor
                │   ├── acop.cov
                │   ├── acop.cpu
                │   ├── acop.ext
                │   ├── acop.grd
                │   ├── acop.lst
                │   ├── acop.mod.out
                │   ├── acop.phi
                │   ├── acop.sh
                │   ├── acop.shk
                │   ├── acop.shm
                │   └── bbi_config.json
                ├── acop.csv
                ├── acop.mod
                └── babylon.yaml
```

So here's what I've found. If you're calling directories relatively, what happens is that after the nonmem work is done, a file is created in the directory **above** where the original model file was created. 

In Devin's situation it was called `examp`, in mine it was `tm` which leads me to believe that somehow it's derivative of the directory name itself.

**Comment by shairozan** [comment]
The contents of the file are also the XML log from nonmem

**Comment by shairozan** [comment]
```xml
<nm:estimation_options
 nm:estim_omitted='no' nm:analysis_type='pop' nm:saddle_reset='0' nm:saddle_hess='0' nm:slow_gradient='noslow'
 nm:cond_estim='yes' nm:centered_eta='no' nm:epseta_interaction='yes' nm:laplace='no' nm:predflag='0' nm:maxfn='9999'
 nm:nsig='3' nm:msfo='no' nm:abort='no' nm:objsort='no' nm:numder='0' nm:optmap='0' nm:etader='0' nm:mceta='0' nm:siglo='100'
 nm:sigl='100' nm:noprior='0' nm:nocov='0' nm:dercont='0' nm:atol='0' nm:fnleta='1' nm:etastype='0' nm:noninfeta='0'
 * nm:file='/users/dbreeden/go/src/github.com/metrumresearchgroup/babylon/cmd/bbi/tmp/tmp/tm' * nm:notitle='0'
 nm:nolabel='0' nm:format='s1pe12.5' nm:order='tsol' nm:wishtype='0' nm:knuthsumoff='0' nm:lntwopi='0' nm:priorc='0'
 nm:olntwopi='0' nm:ctype='0'
```

The estimation_information section of that file lists the file as a target.

**Comment by shairozan** [comment]
Looks like this model has an estimation method set
```
$EST METHOD=1 INTERACTION MAXEVAL=9999 SIG=3 PRINT=5 NOABORT POSTHOC
```

Where as the model I've been primarily working with has it slightly differently listed

```
$ESTIMATION METHOD=1 MAXEVAL=9999 NSIG=3 SIGL=9
```

**Comment by shairozan** [comment]
Based on information from @dpastoor, this is apparently an issue with Nonmem and only expressed in MacOS

**Comment by dpastoor** [comment]
we've established this was an artifact of nonmem's buffers and absolute paths. Not mac os specific, but rather happened to be on my machine in a deeply nested folder. This happens on ubuntu as well. Solution was to change invocations to be relative paths, eg nmfe74 input output rather than nmfe74 abspath/to/input
