### ISSUE TITLE
Post Execution Notification Process

### ISSUE THREAD

**Issue by shairozan** [metrumresearchgroup/babylon#107]
We want to be able to handle the processing / execution of any binary after a job finishes.

# Environment Variables
Much like how Jenkins, Github et all operate, what makes sense is to execute a shell to call the command referenced by the user, but set a large volume of environment variables in the thread. 

* BABYLON_MODEL_PATH : Fully qualified path to the directory in which the original model was located
* BABYLON_MODEL : Full name (file + ext) of model. `file.mod`
* BABYLON_MODEL_FILENAME : First part of the filename. IE if model is `file.mod`, this would be `file`
* BABYLON_MODEL_EXT : Extension of the filename. IE if model is `file.mod`, this will be `mod`
* BABYLON_OUTPUT_DIR : The directory into which the model was placed and ran
* BABYLON_SUCCESSFUL : Whether or not an error occurred. TRUE if completed without error. Error if errors were encountered.
* BABYLON_ERROR : If an error occurred, any error generated (Default "")

# Process

## Successful Models
For models that progress through work phases cleanly and enter cleanup, this can be handled sanely by calling the remote value (if present in config) at the end of the cleanup phase after the completed message has been put on the turnstile channel

## Errored Models
During the postWorkNotice, which basically prints summary details to the console, we know how many errors et all are present based on the errors counter and the errors list on the turnstile manager. One level up, we also have the full list of NonMem models which were used for execution. 

In the event of failures, after execution has been completed for all models (IE 6 successful, three failures), We would look at the failures, find their NonMem Model by identifier in the Concurrent Error stack on the Turnstile manager, and then perform the same process of setting environment variables and calling the exec.

**Comment by shairozan** [comment]
Another option is to basically encode the entire NonMemModel (Including configuration) into Environment Variables. That would be a scenario where we present infinitely more data than may be initially used, but you wouldn't have to worry about **not having** something

**Comment by shairozan** [comment]
@dpastoor Is this something kind of what you were looking for in regards to post-execution hooks? Or would you rather execute webhooks directly? We can actually enable both just encode the same data for both.

**Comment by dpastoor** [comment]
YES! this is exactly the general approach I was thinking. I haven't looked closely at this yet, and can give deeper thoughts later - but definitely going in the right direction!

**Comment by shairozan** [comment]
@dpastoor I've got a working sample of this in #148. Haven't gotten to testing for the SGE phase. Will get to that tomorrow morning.

**Comment by shairozan** [comment]
Working in SGE as well.

**Comment by shairozan** [comment]
Merged into develop
