### ISSUE TITLE
panic error when incomplete model output available

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/babylon#109]
The following command
```
$ bbi nonmem summary example/1/1.ctl \
> --no-cor-file \
> --no-cov-file \
> --no-shk-file
```
throws the following error:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/metrumresearchgroup/babylon/parsers/nmparser.ModelOutput.Summary(0xc00002a3b8, 0x5, 0x1579ef4, 0xa, 0xc000024b80, 0x1c, 0x3fe4cccccccccccd, 0xc1cdcd64ff800000, 0x197, 0x400a666666666666, ...)
	/Users/devinpastoor/go/src/github.com/metrumresearchgroup/babylon/parsers/nmparser/summary.go:26 +0x2355
github.com/metrumresearchgroup/babylon/cmd.summary(0x19824e0, 0xc000078bc0, 0x1, 0x4)
	/Users/devinpastoor/go/src/github.com/metrumresearchgroup/babylon/cmd/summary.go:50 +0x21a
github.com/spf13/cobra.(*Command).execute(0x19824e0, 0xc000078b00, 0x4, 0x4, 0x19824e0, 0xc000078b00)
	/Users/devinpastoor/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1981ae0, 0x12, 0xc000133f00, 0x1)
	/Users/devinpastoor/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/devinpastoor/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/metrumresearchgroup/babylon/cmd.Execute(0x0, 0x0)
	/Users/devinpastoor/go/src/github.com/metrumresearchgroup/babylon/cmd/root.go:61 +0xe5
main.main()
	/Users/devinpastoor/go/src/github.com/metrumresearchgroup/babylon/cmd/bbi/main.go:17 +0x39
```

**Comment by shairozan** [comment]
Should be an easy enough process. The app seems to expect content in the slice without any evaluation. I'll dig into this right after I finish up the delay timers

**Comment by shairozan** [comment]
@dpastoor As a question, when nonmem runs on Windows, how are the datestamps setup on a completed model? It looks like the values on Mac / Linux are using the built-in date functionality. I can sanely test for success in 'Nix systems by reading the last line of the file and seeing if date can parse it, but would that be overly limiting for windows systems? I also have a regex to validate the value, but it all depends on whether or not the Nonmem output on Windows has the same structure for completion time.

**Comment by dpastoor** [comment]
This is a bug I somewhat purposefully introduced when restructuring the internal parsing behavior. @shairozan no need to do anything with this until we can connect, I can tell you exactly what's wrong and what else needs changing. I had Seth post this issue quickly as a breadcrumb to revisit while we were screen sharing

**Comment by dpastoor** [comment]
this has been refactored with proper error messages when missing files
