### ISSUE TITLE
consider model submission delay timers (nm error below)

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/babylon#110]
when submitting a large number of models that all access the same underlying dataset, got the following error on a couple:

```
 WARNINGS AND ERRORS (IF ANY) FOR PROBLEM    1
             
 (WARNING  2) NM-TRAN INFERS THAT THE DATA ARE POPULATION.
  620  ERROR HAS OCCURRED WHILE CLOSING/DELETING FILE   FWORK         
```

My guess is there was read contention on the underlying dataset, and we may want to expose some way to jitter, delay the submission of models. This would only present in very particular situations so definitely wouldn't be worth slowing down the sleep for submissions always.

**Comment by shairozan** [comment]
This has been implemented with the `--delay` flag. When provided a value such as 10 (default is 0), a random float64 is selected between 1 and that value for each turnstile execution. This introduces a random jitter to the start phase, minimizing the collision domain for attempting to read the source file too frequently
