### ISSUE TITLE
Update Qsub for SGE to place grid outputs into OutputDir

### ISSUE THREAD

**Issue by shairozan** [metrumresearchgroup/babylon#112]
Currently when executing on the grid, the grid engine is placing the output for the scripts (stdout / stderr etc) into ~/<scriptname>.[o|e]<JobNumber>

It would be cleaner to have these files placed into the output dir from the model with the rest of the results

**Comment by shairozan** [comment]
This is proving exceptionally painful, but only in parallel scenarios. If I submit to the grid requesting a single slot, 

* `-e`
* `-o` 

Both work. The jobs run and generate their respective files in the output dir. Even using `-j y` to merge the streams works. 

Once the job is submitted as a parallel job, however:

`-V -pe orte 4 -j y -o /data/240/009/sge.output grid.sh`

It gets scheduled, but then dies. There's an **empty** output file in the directory, but the model file and all other files have been removed from the directory

**Comment by shairozan** [comment]
Also has nothing to do with whether or not we're in that directory. I've set the target of the script to submit to be absolute and removed the need to change directory to the script location. No affect

**Comment by shairozan** [comment]
# Non Parallel
![sge_non_parallel 2020-01-20 14_20_47](https://user-images.githubusercontent.com/952951/72752450-39d7e100-3b90-11ea-99ec-bf7a7eec56ac.gif)


# Parallel
![sge_parallel 2020-01-20 14_21_46](https://user-images.githubusercontent.com/952951/72752482-4825fd00-3b90-11ea-97ba-be5c367e1e97.gif)

**Comment by shairozan** [comment]
Figured it out. So I have 4 defined test scenarios that are scripted out:

*`local.sh`
* `parallel.sh`
* `sge.sh`
* `psge.sh`

Each is just a shell script that:

* Deletes the directory in which work is done
* Untars all of the models
* Initializes with `bbi init`
* And then issues the bbi nonmem run command

The psge script I was using was still setting overwrite to true, meaning during the setup phase it was actually blowing everything away. Means we may need to look at a few things:

1. Indicate that based on overwrite settings the directory is being destroyed
2. Possibly not even do anything with overwrite on SGE. I can't think of a scenario in which that combination of commands makes sense. SGE should not remove anything, but rather just set everything up for local to operate, which will read that setting from config

**Comment by shairozan** [comment]
@dpastoor Does it even make sense to provide overwrite functionality on the SGE job? It makes sense to collect and store the data into the config, but I can't think of a scenario where we would be like "Yeah let's totally delete the contents of this directory before submitting something to the grid"

**Comment by dpastoor** [comment]
>  Does it even make sense to provide overwrite functionality on the SGE job?

Yes, if a run already exists and is submitted as an SGE job, I would expect the behavior to be that during the SGE process, that dir would be deleted, a new dir created, and the grid.sh added/submitted. Vice versa if overwite = FALSE it would error before creating the grid.sh and not submit any work

**Comment by shairozan** [comment]
So figuring out where this is causing issues is still not very functional. I've added trace logging to just about every component of the application (Even just an echo statement to the generated script that calls 
`bbi nonmem local run...`

But still seeing the same issue. It gets submitted, "runs" and then the output directory is completely empty. Not even the echo statement from the script is in the output file created

**Comment by shairozan** [comment]
So, there's something more problematic going on I've got to figure out. With the new logging / tracing we have the details for all the files created, commands used to submit them etc. 

So to test and make sure it's nothing wrong with babylon local, I created the exact same bash file in /tmp and submitted it with the same flags. It ran fine without issue. 

So then I got SGE to generate the grid.sh and stopped execution. Then I tried to manually submit it with the exact same flags:

`/opt/sge/bin/lx-amd64/qsub -V -pe orte 4 -j y -o /data/240/009/sge.output.$JOB_ID /data/240/004/grid.sh` and that  worked **perfectly fine**

So how is that same command executed (to submit to the grid and then run) failing in this context?

**Comment by shairozan** [comment]
> > Does it even make sense to provide overwrite functionality on the SGE job?
> 
During the SGE process, that dir would be deleted, a new dir created, and the grid.sh added/submitted. Vice versa if overwite = FALSE it would error before creating the grid.sh and not submit any work

That's fine for the scope of the SGE execution, but what will happen is that the configuration (including the overwrite false) will be written and saved for the purpose of the local execution branch. Should we leave that as overwrite (Which will delete grid.sh etc in the directory), or in the SGE path forcibly set overwrite to false before it saves the config.

Otherwise we're deleting the directory twice.

**Comment by shairozan** [comment]
So for an update, if we take all of the execution of local out of the question (it's never getting started), I've found the following:

- If the output file (or working directory) is specified to the output directory of the model work
    - Whether specified as special flag in script
    - Or by flag directly attached to qsub
    - For any mode of SGE operation (Parallel or not)
    - The job begins, and ends with no execution output
- If *any other* directory is specified for the output file or working directory, it finishes and creates the output files

**Comment by shairozan** [comment]
It is something with the application or it not being able to run the application. If I update the script to include bash components before (at least sleep) I can see the job takes X time before it does, but anything that interacts with std out (like an echo statement) never seems to process

**Comment by shairozan** [comment]
```
darrellb@ip-10-0-1-222:/data$ cat 240/001/sge.output
darrellb@ip-10-0-1-222:/data$ cd tmp/
darrellb@ip-10-0-1-222:/data/tmp$ ls
someoutput
darrellb@ip-10-0-1-222:/data/tmp$ cat someoutput
time="2020-01-21T19:34:13Z" level=info msg="Beginning Babylon!"
time="2020-01-21T19:34:13Z" level=info msg="Beginning Babylon!"
time="2020-01-21T19:34:13Z" level=info msg="Beginning Local Path"
time="2020-01-21T19:34:13Z" level=info msg="Beginning Local Path"
time="2020-01-21T19:34:13Z" level=info msg="Configuration file successfully loaded from /data/240/babylon.yml"
time="2020-01-21T19:34:13Z" level=info msg="Configuration file successfully loaded from /data/240/babylon.yml"
time="2020-01-21T19:34:13Z" level=info msg="A total of 1 models have been located for work"
time="2020-01-21T19:34:13Z" level=info msg="A total of 1 models have been located for work"
time="2020-01-21T19:34:13Z" level=info msg="1 models successfully completed initial setup phase."
time="2020-01-21T19:34:13Z" level=info msg="1 models successfully completed initial setup phase."
time="2020-01-21T19:34:13Z" level=info msg="Manager Details: Working: 0, Errors: 0, Completed: 0, Concurrency: 1, Iterations: 1"
time="2020-01-21T19:34:13Z" level=info msg="Manager Details: Working: 0, Errors: 0, Completed: 0, Concurrency: 1, Iterations: 1"
time="2020-01-21T19:34:13Z" level=error msg="1 errors were experienced during the run"
time="2020-01-21T19:34:13Z" level=error msg="1 errors were experienced during the run"
time="2020-01-21T19:34:13Z" level=error msg="Errors were experienced while running model 002.mod. Details are An error occured trying to remove the directory as specified in the overwriteflag"
time="2020-01-21T19:34:13Z" level=error msg="Errors were experienced while running model 001.mod. Details are An error occured trying to remove the directory as specified in the overwriteflag"
time="2020-01-21T19:34:13Z" level=info msg="\r1 models completed in 27.192057ms"

time="2020-01-21T19:34:13Z" level=info msg="\r1 models completed in 26.898424ms"```

at least a lead. I took the script itself and manually had it redirect stderr into stdout and write to a file. Got the above.

**Comment by shairozan** [comment]
So for some reason afero.RemoveAll is returning "Directory not empty" even though `RemoveAll` is supposed to recursively delete a directory

**Comment by shairozan** [comment]
```
ttime="2020-01-21T20:04:12Z" level=error msg="unlinkat /data/240/001/.nfs00000000000c004b000001de: device or resource busy"
time="2020-01-21T20:04:12Z" level=error msg="unlinkat /data/240/003/.nfs00000000000c004c000001dd: device or resource busy"
time="2020-01-21T20:04:12Z" level=error msg="unlinkat /data/240/001/.nfs00000000000c004b000001de: device or resource busy"
time="2020-01-21T20:04:12Z" level=error msg="1 errors were experienced during the run"
0000000c004d000001d1: device or resource busy"
time="2020-01-21T20:04:12Z" level=error msg="unlinkat /data/240/004/.nfs00000000000c004e000001d0: device or resource busy"
```

And the root of the problem

**Comment by shairozan** [comment]
The directory has a hidden .nfs marker that's locked for some reason

**Comment by shairozan** [comment]
What I think is happening is the following:

1. qsub puts job in queue
2. Worker starts job, starts streams and writes them to file in output directory
3. Worker starts script in job
4. Job then tries to delete the directory, but cannot because the grid manager still has a lock on a file in that directory

**Comment by shairozan** [comment]
In order to sanely handle this and keep the files in the output directory, I'll need to create the -o targets as 

`/originalModelDir/sge.output.<ModelFileName>.$JOB_ID`

We'll need the prefix of `/originalModelDir/sge.output.<ModelFileName>.` in order to use `afero.Glob` on the original directory, locate the files, copy them into the child directories and then delete them from the original model dir.
