### ISSUE TITLE
error before can parse config if --config is explicitly set

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/babylon#124]
```
⋊> ~/c/m/d/n/e/n/acop bbi nonmem run local acop.ctl --config=../babylon.yml --debug --verbose                                                             15:34:04
INFO[0000] Beginning Local Path                         
DEBU[0000] Locating models from arguments               
FATA[0000] A failure: open /Users/devinp/clients/metrum/devinp/nonmem-examples/example-models/nonmem/acop/babylon.yaml: no such file or directory, occurred accessing the initial configuration at /Users/devinp/clients/metrum/devinp/nonmem-examples/example-models/nonmem/acop/babylon.yam
```

Tracing it shows this to be the FATAL location (note: the additional `open /Users/devinp/clients/metrum/devinp/nonmem-examples/example-models/nonmem/acop/babylon.yaml:` component of the error message was an added log statement)

https://github.com/metrumresearchgroup/babylon/blob/master/cmd/nonmem.go#L683

I propose that after the initial read of the config, there should be no need to read the config in again, rather in all places information from the config would be needed the config object or relevant components should be passed in.

**Comment by dpastoor** [comment]
Three immediate testing scenarios that we'd want to make successful

### relative path

```
bbi nonmem run local acop.ctl --config=../babylon.yml --debug --verbose
```

### relative path, where model is also in subfolder

```
bbi nonmem run local acop/acop.ctl --config=../babylon.yml --debug --verbose
```

### absolute path

```
bbi nonmem run local acop.ctl --debug --verbose --config=/Users/devinp/clients/metrum/devinp/nonmem-examples/example-models/nonmem/babylon.yaml     
```

**Comment by shairozan** [comment]
Both absolute and relative paths are covered in the new approach to config management. We have a test for both the default path (locally to the execution dir) as well as an absolute path specification. I will also write a test to accomodate relative file selection

**Comment by shairozan** [comment]
I added a test to verify these three test scenarios for the babylon functional testing:

- No config is specified (Default local babylon.yaml)
- Config is specified via absolute path
- Config is specified via relative path (up or down)

**Comment by shairozan** [comment]
Implemented
