### ISSUE TITLE
improper expansion of numbered runs without prefix

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/babylon#160]
Attempt to submit run 100-200 via:

![image](https://user-images.githubusercontent.com/3196313/79135594-9ad11880-7d7d-11ea-89dd-ae2d4976c544.png)

Notice error was run 1 was going to be the attempted first submission - so the regex parsing the numbers is incorrect. (I believe when I wrote it I was expecting syntax like `run[100:200].ctl`

I did locally test the ExpandSequence function

```
		{"[100:110].ctl", []string{"100.ctl", "101.ctl", "102.ctl", "103.ctl", "104.ctl", "105.ctl", "106.ctl", "107.ctl", "108.ctl", "109.ctl", "110.ctl"}},
```

and the test passes, so I believe the issue is upstream in `cmd/nonmem.go`

around line 866

```
	if len(r.FindAllStringSubmatch(arg, 1)) > 0 {
				log.Infof("expanding model pattern: %s \n", arg)
				pat, err := utils.ExpandNameSequence(arg)
				if err != nil {
					log.Errorf("err expanding name: %v", err)
					// don't try to run this model
					continue
				}
```

I don't think this is properly hitting, esp given we're never seeing the log messages for `log.Infof("expanding model pattern: %s \n", arg)`

**Comment by shairozan** [comment]
Can you confirm the version of Babylon you're using? I just did this exact same scenario with the 2.1.0 release `[100:200].ctl` in both local and SGE modes without any expansion errors. 
![Screen Shot 2020-04-13 at 1 10 17 PM](https://user-images.githubusercontent.com/952951/79141599-264fa700-7d88-11ea-804b-a32e6432d414.png)

Could you also provide the contents of your babylon.yaml?

**Comment by dpastoor** [comment]
hmmm....

<img width="1264" alt="Screen Shot 2020-04-13 at 1 26 13 PM" src="https://user-images.githubusercontent.com/3196313/79143042-81829900-7d8a-11ea-9b46-920e5ce3368c.png">

<img width="1264" alt="Screen Shot 2020-04-13 at 1 27 00 PM" src="https://user-images.githubusercontent.com/3196313/79143054-86474d00-7d8a-11ea-9a6f-b4c9da47d901.png">

**Comment by dpastoor** [comment]
Follow-up - this seems to be an issue with the bash interpreter

```
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

switching to fish and this works fine. What is confusing as what is different about my config causing this. Solution is to quote the argument:

```
/data/apps/bbi nonmem run sge "[100:102].ctl"
```
