### ISSUE TITLE
Estimate of Sigma (2,1) is displayed as 0 in model when it shouldn't be displayed

### ISSUE THREAD

**Issue by adamlafontaine** [metrumresearchgroup/babylon#163]
Originally submitted as issue [here](https://github.com/metrumresearchgroup/rbabylon/issues/62) for rbabylon. However it appears that the estimate is being returned as part of the NONMEM summary when it shoudnt and that is why rbabylon is picking it up and displaying it when it shouldn't.

### Original Issue

In a model where the $SIGMA starting values were not specified as a block, displaying the the parameter estimates with the following command resulted in the table below. After talking with Matt and @callistosp the inclusion of SIGMA(2,1) is not the preferred behavior. 

```text
model_summary(mod104) %>%
  param_estimates()
```

names| estimate|stderr |fixed
-------|------|------|------
OMEGA(3,3) | 0.1693070 | 1.97401e-02 | 0 |  
SIGMA(1,1) | 0.0397749 | 1.25788e-03 | 0 |  
SIGMA(2,1) | 0.0000000 | 1.00000e+10 | 1 |  
SIGMA(2,2) | 0.8410060 | 2.87706e+00 | 0 |

In the .ctl file the starting values for $SIGMA were not specified as a block.

$SIGMA
0.05     ; 1 pro error
0.05     ; 2 add error

## .lst file output

```text
FINAL PARAMETER ESTIMATE

 SIGMA - CORR MATRIX FOR RANDOM EFFECTS - EPSILONS  ***


         EPS1      EPS2     
 
 EPS1
+        1.99E-01
 
 EPS2
+        0.00E+00  9.17E-01

STANDARD ERROR OF ESTIMATE

SIGMA - CORR MATRIX FOR RANDOM EFFECTS - EPSILONS  ***


         EPS1      EPS2     
 
 EPS1
+        3.15E-03
 
 EPS2
+       .........  1.57E+00
```

**Comment by dpastoor** [comment]
This is something that actually needs to get addressed in rbabylon - the fact is that parameter is returned in the EXT file as part of the params (same as off diagonal omega elements). This is not helpful the vast majority of the time for sigma, but is not invalid and is reasonable syntax (you can do SIGMA BLOCK(x))

This likely should be filtered by default in the param_summary() func in rbabylon, but shouldn't be suppressed from the raw data
