### ISSUE TITLE
Whitespace removed from end of .ctl file after NONMEM run

### ISSUE THREAD

**Issue by adamlafontaine** [metrumresearchgroup/babylon#168]
Trailing whitespace appears to be removed as a result of running a NONMEM .ctl file. We believe this is an issue associated with babylon as the change does not occur when run using other tools.
&nbsp;

colordiff 100.ctl 100/100.ctl

<img width="557" alt="Screen Shot 2020-05-14 at 1 39 19 PM" src="https://user-images.githubusercontent.com/63752449/81971282-d7976600-95ee-11ea-9e5c-edd9ec444ed3.png">
 &nbsp;

This can cause issues when trying to check for file changes by comparing the hashes of the .ctl files outside and inside of the individual run folder. The result is that all files appear as if they have changed even immediately following a model run.

<img width="741" alt="Screen Shot 2020-05-14 at 1 48 16 PM" src="https://user-images.githubusercontent.com/63752449/81971274-d49c7580-95ee-11ea-9000-76db514249b1.png">

**Comment by dpastoor** [comment]
We have identified this is an issue in how we are copying the file into the run directory. Thanks for the heads up - we will update with a patch!

**Comment by dpastoor** [comment]
per discussion with @shairozan - likely best to just pre-hash the file before copying rather than trying to think of all cases that could change during copying - plus account for the .mod vs .ctl data injection differences.

**Comment by adamlafontaine** [comment]
I agree. Would the hash be stored somewhere in the the yaml then?

**Comment by shairozan** [comment]
It's not by default as they're not a configuration option. I will have to make sure that they are persisted somehow between local execution phases and the SGE phase. Gotta thing through the best approach for it.

**Comment by dpastoor** [comment]
This is now addressed for ctl files by switching the read/write implementation to make sure its a clean copy if there is no need to modify the data path. We still may need to address more holistically to consider .mod files as well, but as @shairozan mentioned this will take some more planning around the sge/local interactions
