### ISSUE TITLE
Additional fields in bbi nonmem summary

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/babylon#175]
As a user, I would like to have some additional fields extracted and added to the output of `bbi nonmem summary ... --json`:

* **ofv** -- Currently includes the objective function value for the last estimation method. Please include all estimation methods.
* **condition_number** -- The condition number. This will only be in the .lst file in certain cases (when scientists ask for it in the $COV block `PRINT=E`). There will be one for each estimation method. If any of them are large, the heuristic flag should be triggered.
* **eta_pval_significant** -- Add to `run_heuristics`. `TRUE` if any pval < 0.05. Extracted from `bbi_summary$shrinkage_details`. Will be `FALSE` if no shrinkage file present.
* **PRDERR** -- T/F in `run_heuristics`, whether a PRDERR file was created by the run.

**Comment by seth127** [comment]
# Questions

## ofv

* Do we really need the constant and the objective with constant? It would simplify parsing to get rid of them. If they are used/needed we'll keep them, but if not let's toss them.
* If we do keep them, what about in cases like this, with SAEM:
```
 TOTAL DATA POINTS NORMALLY DISTRIBUTED (N):         7006
 N*LOG(2PI) CONSTANT TO OBJECTIVE FUNCTION:    12876.166727263873     
 OBJECTIVE FUNCTION VALUE WITHOUT CONSTANT:    21589.980830105564     
 OBJECTIVE FUNCTION VALUE WITH CONSTANT:       34466.147557369433     
 REPORTED OBJECTIVE FUNCTION DOES NOT CONTAIN CONSTANT
  
 TOTAL EFFECTIVE ETAS (NIND*NETA):                          1744
 NIND*NETA*LOG(2PI) CONSTANT TO OBJECTIVE FUNCTION:    3205.2576038178981     
 OBJECTIVE FUNCTION VALUE WITHOUT CONSTANT:    21589.980830105564     
 OBJECTIVE FUNCTION VALUE WITH CONSTANT:       24795.238433923463     
 REPORTED OBJECTIVE FUNCTION DOES NOT CONTAIN CONSTANT
```

# condition number

* do we want it for all estimation methods or just the final one?
* if all, should the "large" flag check all of them, or just the one for the final method?
* is 1000 a good "large" limit?

# ETA p-val

* do we check for all p-vals for all estimation methods or just the final one?

**Comment by seth127** [comment]
> do we check for all p-vals for all estimation methods (and all subpops) or just the final one?
@anarpkpd says just the last one is fine

**Comment by kylebaron** [comment]
@seth127 

- Seems like we should never take the objective function value from an SAEM run
- Do we need the constant: I can think of some situations where we would like to objective function value with the constant, but I don't think these are immediate needs; could we bypass for now and re-evaluate for later?  I feel like that would be wise use of resources but might be a different calculation if we couldn't ask for it later on
- Condition number for final method seems ok for me 
- Condition number where 1000 = big 
  - this seems a bit small
  - In Pete Bonate's book, condition number between 1e4 and 1e6 indicate moderate collinearity; more than 1e6 is severe; obviously there are other sources out there and different opinions (Ken)
  - Maybe 1e4 or 1e5?  I'm thinking that if it is 1e3 we'll have large condition number every time

**Comment by riggsmm** [comment]
per condition number (in support of 1000 as a flag (not to flat out reject, but to investigate)):
- 1000 is the number that always stuck in my mind: per Ken Kowalski https://www.cognigen.com/nonmem/nm/99may012003.html … 
- though, Diane Mould’s paper uses the sqrt of the ratio and suggests that if that number is >= 100, then there’s high colinearity (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3636497/#bib26)
- Pete Bonate, here, uses 1000: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3475847/

**Comment by kylebaron** [comment]
@seth127 consensus from the team to go with 1000 as large condition number.

**Comment by seth127** [comment]
Ok, I think I have most of these done. For the objective function, this is **old** printout
```
"ofv":
		{
			"ofv_no_constant": 29721.412,
			"ofv": 12876.166727263873,
			"ofv_with_constant": 42597.57867068325
		}
```

and this is the **new** printout
```
"ofv": [
		{
			"method": "Stochastic Approximation Expectation-Maximization",
			"ofv_no_constant": 21589.981,
			"constant_to_ofv": 3205.257603817898,
			"ofv_with_constant": 24795.238433923463
		},
		{
			"method": "Objective Function Evaluation by Importance Sampling",
			"ofv_no_constant": 29721.412,
			"constant_to_ofv": 12876.166727263873,
			"ofv_with_constant": 42597.57867068325
		}
	]
```

_note:_ I don't know why the constant used to be called `"ofv"` in the json, but I changed it to `"constant_to_ofv"`

**Comment by seth127** [comment]
I realized that I wrote in the original post:

> There will be one [condition number] for each estimation method. If any of them are large, the heuristic flag should be triggered.

But then I asked whether that was necessary and @kylebaron said "no, just checking the final estimation method is good."

I just want to make sure we have consensus on this:

* should we return the condition number itself _for each estimation method_ or just the final one?
* if we return all of them, should the `large_condition_number` flag be triggered only by the final one or by any of them?

**Comment by seth127** [comment]
consensus from @anarpkpd @kylebaron is to do all estimation methods for condition number too (same as objective function).
