### ISSUE TITLE
weirdness with $DATA path for .ctl files when there is no ../ in the path

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/babylon#195]
Near here: https://github.com/metrumresearchgroup/babylon/blob/develop/cmd/nonmem.go#L750 where we do `strings.Replace(basefilePath, "../", "", 1)`, this will do nothing if they specify a `$DATA` with no `../` in front of it. 

This would technically be invalid for a `.ctl` because it's supposed to be from the perspective of the output dir (and how could your data be in your output dir?...) but it passes [this first check](https://github.com/metrumresearchgroup/babylon/blob/fix/period-in-model-path/cmd/nonmem.go#L769) (a few lines later with `dataFileIsPresent`) and then fails with a NONMEM error when it runs:
```
$ bbi nonmem run local Executable_MTP.ctl --nm_version=nm74gf --overwrite
INFO[0000] Successfully loaded default configuration from /data/SethTest/working/ctl_test/babylon.yaml 
INFO[0000] Beginning Local Path                         
INFO[0000] A total of 1 models have completed the initial preparation phase 
INFO[0000] [Executable_MTP] Beginning local work phase  
ERRO[0000] [Executable_MTP] Exit code was 107, details were exit status 107 
ERRO[0000] [Executable_MTP] output details were: Starting NMTRAN
  
 WARNINGS AND ERRORS (IF ANY) FOR PROBLEM    1
             
 (WARNING  2) NM-TRAN INFERS THAT THE DATA ARE POPULATION.
 
 AN ERROR WAS FOUND IN THE CONTROL STATEMENTS.
 
 THE CHARACTERS IN ERROR ARE: 
 Data.csv                                                                        
   33  INPUT DATA FILE DOES NOT EXIST OR CANNOT BE OPENED. 
INFO[0000] Waiting for any post execution hooks to finish 
ERRO[0000] 1 errors were experienced during the run     
ERRO[0000] Errors were experienced while running model Executable_MTP.ctl. Details are Running the programmatic shell script caused an error 
1 models completed in 97.763307ms           
```
(this ^ is with `$DATA Data.csv` instead of `$DATA ../Data.csv` which would be correct)

But when I change it to `$DATA ../../Data.csv` (which is wrong in the other direction) then it _does_ get caught by `dataFileIsPresent` and we get this error:
```
sethg@ip-10-128-53-8:/data/SethTest/working/ctl_test$ vim Executable_MTP.ctl 
sethg@ip-10-128-53-8:/data/SethTest/working/ctl_test$ bbi nonmem run local Executable_MTP.ctl --nm_version=nm74gf --overwrite
INFO[0000] Successfully loaded default configuration from /data/SethTest/working/ctl_test/babylon.yaml 
INFO[0000] Beginning Local Path                         
FATA[0000] An error occurred during model processing: unable to open datafile at /data/SethTest/working/Data.csv referenced in model file Executable_MTP.ctl. Error details are open /data/SethTest/working/Data.csv: no such file or directory
```

So I guess it's not _really_ a problem at all. Just weird.

**Comment by seth127** [comment]
I'm gonna close this because I don't think it's really an issue we care about. I just spent awhile chasing it though and I have a premonition that I'm gonna want to retrieve this memory at some point in the future, so I documented it here.

**Comment by Mutaz94** [comment]
Hi Seth; just want to add to the list, not only `*.ctl`, also `*.txt` won't work and give this error as well. When switching to `*.mod` it gives a reasonable run without error in hand. I use bbi v3.0

**Comment by seth127** [comment]
Thanks @Mutaz94 . Are you saying that your control stream has the extension `.txt`? Forgive my ignorance, but I didn't realize that was a valid extension for NONMEM. 

If that's right, we'll reopen this (or maybe open a new issue) and address that.

**Comment by Mutaz94** [comment]
Hi Seth! Yes, NONMEM can accept `*.txt` as an extension or surprisingly any extension with taken into consideration the correct format of the control stream.
