### ISSUE TITLE
Panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by annacnev** [metrumresearchgroup/babylon#32]
[exercise_contpkpd_example_1ctl.zip](https://github.com/metrumresearchgroup/babylon/files/3642467/exercise_contpkpd_example_1ctl.zip)
**Terminal Output**

```
bbi run 1.mod
```

Response:

```
>adding model 1.mod to queue
>running on 8 threads took 7.839437751s
```

```
bbi summary 1
```

Response:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/metrumresearchgroup/babylon/parsers/nmparser.ModelOutput.Summary(0xc0000281b8, 0x5, 0xc0000245e0, 0x1c, 0xc000024f80, 0x1c, 0x4002147ae147ae14, 0x3fbeb851eb851eb8, 0x1aa, 0x400e666666666666, ...)
	/Users/devinpastoor/go/src/github.com/metrumresearchgroup/babylon/parsers/nmparser/summary.go:78 +0x2856
github.com/metrumresearchgroup/babylon/cmd.summary(0x1931640, 0xc0000ae740, 0x1, 0x1)
	/Users/devinpastoor/go/src/github.com/metrumresearchgroup/babylon/cmd/summary.go:50 +0x210
github.com/spf13/cobra.(*Command).execute(0x1931640, 0xc0000ae6f0, 0x1, 0x1, 0x1931640, 0xc0000ae6f0)
	/Users/devinpastoor/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1930ec0, 0x12, 0xc00017df00, 0x1)
	/Users/devinpastoor/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/devinpastoor/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/metrumresearchgroup/babylon/cmd.Execute(0x0, 0x0)
	/Users/devinpastoor/go/src/github.com/metrumresearchgroup/babylon/cmd/root.go:54 +0xe5
main.main()
	/Users/devinpastoor/go/src/github.com/metrumresearchgroup/babylon/cmd/bbi/main.go:17 +0x39

```

**Comment by david-lyder** [comment]
The 1.lst file does not have shrinkage info in the form that bbi expects. Here is an example of what bbi expects:
IN SHRINKAGE (ETASTYPE):             NO
 ETASHRINKSD(%)  4.0632E-01  2.0606E+00  1.8484E+01
 ETASHRINKVR(%)  8.1099E-01  4.0787E+00  3.3551E+01
 EBVSHRINKSD(%)  4.9256E-01  2.1487E+00  1.8703E+01
 EBVSHRINKVR(%)  9.8269E-01  4.2512E+00  3.3908E+01
 EPSSHRINKSD(%)  9.7026E+00
 EPSSHRINKVR(%)  1.8464E+01

We'll need to add logic to support lst files that do not have shrinkage info.

**Comment by david-lyder** [comment]
**Test results after fix was applied:**
**I. contpkpd output (configuration with the original issue)**
bbi summary 1
RUN# 1 DIRECT POPULATION PKPD MODEL
Dataset: ../pkpd.csv
Records: 460   Observations: 440  Patients: 20
Estimation Method(s):
 - First Order
+-------+------+----------+------------------+
| THETA | NAME | ESTIMATE |   STDERR (RSE)   |
+-------+------+----------+------------------+
| TH 1  | KA   | 3.97038  | 0.615355 (15.5%) |
| TH 2  | CL   | 4.49182  | 0.215561 (4.8%)  |
| TH 3  | V    | 40.6919  | 1.74623 (4.3%)   |
| TH 4  | EMAX | 182.163  | 27.6309 (15.2%)  |
| TH 5  | EC50 | 7.29389  | 1.40321 (19.2%)  |
+-------+------+----------+------------------+
+--------+-----+----------+-----------------+
| OMEGA  | ETA | ESTIMATE | SHRINKAGESD (%) |
+--------+-----+----------+-----------------+
| O(1,1) |     | 1.216750 | 0.000000        |
| O(2,2) |     | 0.034081 | 0.000000        |
| O(3,3) |     | 0.018245 | 0.000000        |
| O(4,4) |     | 3.043970 | 0.000000        |
| O(5,5) |     | 3.940610 | 0.000000        |
| O(6,6) |     | 0.043368 | 0.000000        |
+--------+-----+----------+-----------------+

bbi summary --json 1
{
	"run_details": {
		"version": "7.4.3",
		"run_start": "Mon Sep 23 10:53:28 EDT 2019",
		"run_end": "Mon Sep 23 10:53:33 EDT 2019",
		"estimation_time": 0.2,
		"covariance_time": 0.03,
		"function_evaluations": 406,
		"significant_digits": 3.3,
		"problem_text": "RUN# 1 DIRECT POPULATION PKPD MODEL",
		"estimation_method": [
			"First Order"
		],
		"data_set": "../pkpd.csv",
		"number_of_patients": 20,
		"number_of_obs": 440,
		"number_of_data_records": 460
	},
	"run_heuristics": {},
	"parameters_data": [
		{
			"method": "TABLE NO.     1: First Order: Goal Function=MINIMUM VALUE OF OBJECTIVE FUNCTION: Problem=1 Subproblem=0 Superproblem1=0 Iteration1=0 Superproblem2=0 Iteration2=0",
			"estimates": {
				"theta": [
					3.97038,
					4.49182,
					40.6919,
					182.163,
					7.29389
				],
				"omega": [
					1.21675,
					0,
					0.0340808,
					0,
					0,
					0.0182446,
					0,
					0,
					0,
					3.04397,
					0,
					0,
					0,
					0,
					3.94061,
					0,
					0,
					0,
					0,
					0,
					0.0433683
				],
				"sigma": [
					0.060817,
					0
				]
			},
			"std_err": {
				"theta": [
					0.615355,
					0.215561,
					1.74623,
					27.6309,
					1.40321
				],
				"omega": [
					0.323389,
					10000000000,
					0.0113267,
					10000000000,
					10000000000,
					0.00726943,
					10000000000,
					10000000000,
					10000000000,
					0.973793,
					10000000000,
					10000000000,
					10000000000,
					10000000000,
					2.03261,
					10000000000,
					10000000000,
					10000000000,
					10000000000,
					10000000000,
					0.020061
				],
				"sigma": [
					0.00577054,
					10000000000
				]
			},
			"random_effect_sd": {
				"omega": [
					1.10307,
					0,
					0.18461,
					0,
					0,
					0.135073,
					0,
					0,
					0,
					1.7447,
					0,
					0,
					0,
					0,
					1.9851,
					0,
					0,
					0,
					0,
					0,
					0.208251
				],
				"sigma": [
					0.246611,
					0
				]
			},
			"random_effect_sdse": {
				"omega": [
					0.146587,
					10000000000,
					0.0306774,
					10000000000,
					10000000000,
					0.0269093,
					10000000000,
					10000000000,
					10000000000,
					0.279072,
					10000000000,
					10000000000,
					10000000000,
					10000000000,
					0.511967,
					10000000000,
					10000000000,
					10000000000,
					10000000000,
					10000000000,
					0.0481655
				],
				"sigma": [
					0.0116997,
					10000000000
				]
			},
			"fixed": {
				"theta": [
					0,
					0,
					0,
					0,
					0
				],
				"omega": [
					0,
					1,
					0,
					1,
					1,
					0,
					1,
					1,
					1,
					0,
					1,
					1,
					1,
					1,
					0,
					1,
					1,
					1,
					1,
					1,
					0
				],
				"sigma": [
					0,
					1
				]
			}
		}
	],
	"parameter_structures": {
		"Theta": 6,
		"Omega": [
			1,
			0,
			1,
			0,
			0,
			1,
			0,
			0,
			0,
			1,
			0,
			0,
			0,
			0,
			1,
			0,
			0,
			0,
			0,
			0,
			1
		],
		"Sigma": [
			1,
			0,
			1
		]
	},
	"parameter_names": {
		"theta": [
			"KA",
			"CL",
			"V",
			"EMAX",
			"EC50",
			"E0"
		]
	},
	"ofv": {
		"ofv": 808.665909220112,
		"ofv_no_constant": 1637.192,
		"ofv_with_constant": 2445.8583194295575
	},
	"shrinkage_details": {
		"eta": {},
		"ebv": {},
		"eps": {}
	}
}

**II.  BQL (existing configuration that worked before the change)** 
bbi summary 2
LEM RUN# 2 - 2cmpt model - no BQLs
Dataset: ../nobqldata.csv
Records: 2895   Observations: 2702  Patients: 193
Estimation Method(s):
 - First Order Conditional Estimation with Interaction
+-------+----------+----------+--------------------------------+
| THETA |   NAME   | ESTIMATE |          STDERR (RSE)          |
+-------+----------+----------+--------------------------------+
| TH 1  | 1    CLF | 26.4905  | 0.60908 (2.3%)                 |
| TH 2  | 2    V2F | 282.616  | 4.40586 (1.6%)                 |
| TH 3  | 3    V3F | 297.043  | 2.32933 (0.8%)                 |
| TH 4  | 4    QF  | 58.749   | 1.01296 (1.7%)                 |
| TH 5  | 5    KA  | 1.5095   | 0.0212776 (1.4%)               |
| TH 6  | 6 POW_CL | 0.75     | 10000000000 (1333333333333.3%) |
| TH 7  | 7 POW_V2 | 1        | 10000000000 (1000000000000.0%) |
| TH 8  | 8 POW_V3 | 1        | 10000000000 (1000000000000.0%) |
+-------+----------+----------+--------------------------------+
+--------+------+----------+-----------------+
| OMEGA  | ETA  | ESTIMATE | SHRINKAGESD (%) |
+--------+------+----------+-----------------+
| O(1,1) | ETA1 | 0.100611 | 0.406320        |
| O(2,2) |      | 0.035999 | 0.000000        |
| O(3,3) | ETA2 | 0.011173 | 2.060600        |
+--------+------+----------+-----------------+

bbi summary --json 2
{
	"run_details": {
		"version": "7.4.3",
		"run_start": "Wed Sep 11 10:19:21 EDT 2019",
		"run_end": "Wed Sep 11 10:19:35 EDT 2019",
		"estimation_time": 4.04,
		"covariance_time": 0.06,
		"function_evaluations": 189,
		"significant_digits": 3.4,
		"problem_text": "LEM RUN# 2 - 2cmpt model - no BQLs",
		"estimation_method": [
			"First Order Conditional Estimation with Interaction"
		],
		"data_set": "../nobqldata.csv",
		"number_of_patients": 193,
		"number_of_obs": 2702,
		"number_of_data_records": 2895
	},
	"run_heuristics": {},
	"parameters_data": [
		{
			"method": "TABLE NO.     1: First Order Conditional Estimation with Interaction: Goal Function=MINIMUM VALUE OF OBJECTIVE FUNCTION: Problem=1 Subproblem=0 Superproblem1=0 Iteration1=0 Superproblem2=0 Iteration2=0",
			"estimates": {
				"theta": [
					26.4905,
					282.616,
					297.043,
					58.749,
					1.5095,
					0.75,
					1,
					1
				],
				"omega": [
					0.100611,
					0,
					0.035999,
					0,
					0,
					0.0111726
				]
			},
			"std_err": {
				"theta": [
					0.60908,
					4.40586,
					2.32933,
					1.01296,
					0.0212776,
					10000000000,
					10000000000,
					10000000000
				],
				"omega": [
					0.00959481,
					10000000000,
					0.00353287,
					10000000000,
					10000000000,
					0.00186447
				]
			},
			"random_effect_sd": {
				"omega": [
					0.317192,
					0,
					0.189734,
					0,
					0,
					0.1057
				]
			},
			"random_effect_sdse": {
				"omega": [
					0.0151246,
					10000000000,
					0.00931006,
					10000000000,
					10000000000,
					0.00881961
				]
			},
			"fixed": {
				"theta": [
					0,
					0,
					0,
					0,
					0,
					1,
					1,
					1
				],
				"omega": [
					0,
					1,
					0,
					1,
					1,
					0
				]
			}
		}
	],
	"parameter_structures": {
		"Theta": 9,
		"Omega": [
			1,
			0,
			1,
			0,
			0,
			1
		],
		"Sigma": [
			1
		]
	},
	"parameter_names": {
		"theta": [
			"1    CLF",
			"2    V2F",
			"3    V3F",
			"4    QF",
			"5    KA",
			"6 POW_CL",
			"7 POW_V2",
			"8 POW_V3",
			"9 POW_Q"
		]
	},
	"ofv": {
		"ofv": 4965.943833438051,
		"ofv_no_constant": -14346.006,
		"ofv_with_constant": -9380.062196247563
	},
	"shrinkage_details": {
		"eta": {
			"sd": [
				0.40632,
				2.0606,
				18.484
			],
			"vr": [
				0.81099,
				4.0787,
				33.551
			]
		},
		"ebv": {
			"sd": [
				0.49256,
				2.1487,
				18.703
			],
			"vr": [
				0.98269,
				4.2512,
				33.908
			]
		},
		"eps": {
			"sd": [
				9.7026
			],
			"vr": [
				18.464
			]
		}
	}
}

**Comment by dpastoor** [comment]
fix applied in #33 

thanks david @annacnev building a new version now for you to use

**Comment by dpastoor** [comment]
after looking, this is not correct yet, it should provide all zeroes for all shrinkages, similar to stderr related values being all 0 given stderr not estimated. 

The key to establish what omega/epsilon elements are associated with shrinkage is to mimick the side of the ParameterStructures

```
"parameter_structures": {
"Theta": 6,
"Omega": [
1,
0,
1,
0,
0,
1,
0,
0,
0,
1,
0,
0,
0,
0,
1,
0,
0,
0,
0,
0,
1
],
"Sigma": [
1,
0,
1
]
```

all omega/sigmas associated with 1 are user defined parameters with estimated shrinkage, hence by summing the slices can establish the length of the placeholder slices.

**Comment by david-lyder** [comment]
The output with zero shrinkage_details (from example-model IOVMM:
{
	"run_details": {
		"version": "7.4.3",
		"run_start": "Thu Sep 12 13:09:51 EDT 2019",
		"run_end": "Thu Sep 12 13:10:08 EDT 2019",
		"estimation_time": 11.29,
		"covariance_time": 0.6,
		"function_evaluations": 367,
		"significant_digits": 3.1,
		"problem_text": "LEM 10 mixture model and IOV on CL",
		"estimation_method": [
			"First Order"
		],
		"data_set": "../MixSim.CSV",
		"number_of_patients": 300,
		"number_of_obs": 12600,
		"number_of_data_records": 13500
	},
	"run_heuristics": {},
	"parameters_data": [
		{
			"method": "TABLE NO.     1: First Order: Goal Function=MINIMUM VALUE OF OBJECTIVE FUNCTION: Problem=1 Subproblem=0 Superproblem1=0 Iteration1=0 Superproblem2=0 Iteration2=0",
			"estimates": {
				"theta": [
					14.2204,
					100.996,
					0.824135,
					0.988974,
					1.70925
				],
				"omega": [
					0.0490352,
					0,
					0.0482149,
					0,
					0,
					0.0359252,
					0,
					0,
					0,
					0.0359252,
					0,
					0,
					0,
					0,
					0.0359252
				],
				"sigma": [
					0.0458045,
					0
				]
			},
			"std_err": {
				"theta": [
					0,
					0,
					0,
					0,
					0
				],
				"omega": [
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				],
				"sigma": [
					0,
					0
				]
			},
			"random_effect_sd": {
				"omega": [
					0.221439,
					0,
					0.219579,
					0,
					0,
					0.189539,
					0,
					0,
					0,
					0.189539,
					0,
					0,
					0,
					0,
					0.189539
				],
				"sigma": [
					0.21402,
					0
				]
			},
			"random_effect_sdse": {},
			"fixed": {
				"theta": [
					0,
					0,
					0,
					0,
					0
				],
				"omega": [
					0,
					1,
					0,
					1,
					1,
					0,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1,
					1
				],
				"sigma": [
					0,
					1
				]
			}
		}
	],
	"parameter_structures": {
		"Theta": 6,
		"Omega": [
			1,
			0,
			2,
			0,
			0,
			3,
			0,
			0,
			0,
			3,
			0,
			0,
			0,
			0,
			3
		],
		"Sigma": [
			1,
			0,
			1
		]
	},
	"parameter_names": {
		"theta": [
			"1. CL POP 1",
			"2. V",
			"3. WT ON CL",
			"4. WT ON V",
			"5. CL POP 2",
			"6. PROB POP 1"
		]
	},
	"ofv": {
		"ofv": 23157.251036757752,
		"ofv_no_constant": 17485.751,
		"ofv_with_constant": 40643.001566747465
	},
	"shrinkage_details": {
		"eta": {
			"sd": [
				0,
				0,
				0,
				0,
				0
			],
			"vr": [
				0,
				0,
				0,
				0,
				0
			]
		},
		"ebv": {
			"sd": [
				0,
				0,
				0,
				0,
				0
			],
			"vr": [
				0,
				0,
				0,
				0,
				0
			]
		},
		"eps": {
			"sd": [
				0,
				0
			],
			"vr": [
				0,
				0
			]
		}
	}
}

**Comment by dpastoor** [comment]
excellent! LGTM
