### ISSUE TITLE
provide option to run either autolog.pl or native

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/babylon#86]
Note: autolog is what is used to install all versions of nonmem on metworx to date. It does inject some changes to the nmfe batch command to recognize this additional flag `ce`, but that ce is not present if installed via normal SETUP74

I am not sure off the top of my head whether the ce is needed, or just optional, such that it really doesn't need to be included, and it's only important to _not_ include it if the nonmem install was done without nmqual

**Comment by shairozan** [comment]
So from what I can see in the batch files, we're doing the following:

- Checking to see if the first parameter passed to NM is 'c', 'e' or 'ce'
    - From what I can tell these are `compile` and `execute` flags
- If they're present, we set another variable internally that I'm still trying to track down if it's used
- And then we shift that argument off the stack so that it never gets passed to Nonmem if present
- If the first parameter is not a `c` / `e` flag, we define that we'll be operating in mode CE, compile and execute.

**Comment by dpastoor** [comment]
We can check with users, however this is generally a holdout of the past in which licensing restricted use - eg when run naively the fortran intel license would be held through the entire execution phase, when it was really only needed for compilation, such that it gave a chance to break those up. 

This is no longer an (internal) need and most people we interact with have moved to gfortran.

I am not really terribly familiar with all the options autolog even really allows, though I think its not much.

We should start to minimally achieve the following:

```
qsub -N {{name}} -o {{model_folder}} -e {{model_folder}} -V -j y -q queue:{{queue}} -sync y -shell n -b y -cwd -pe orte {{ncores}} perl -S {{path_to_autolog.pl}} {{path_to_nmqual/log.xml}} {{if parallel}} para {{end}} ce {{model_folder}} {{modelname}}
```

I will chase down some of the compilation controls to understand how it should break up the compilation/execution phases separately.

**Comment by shairozan** [comment]
@dpastoor In the latest release, an `nmqual` flag was introduced which runs in `para ce` mode with autolog. Check that out and see if that's what we need or if we need to change anything up

**Comment by shairozan** [comment]
Implemented with the `nmqual` flag
